# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Prakash Natarajan
tagline:          'Personal website'
description:      'CS Graduate Student University at Buffalo'
url:              http://www.prakashn.com
baseurl:          /

author:
  name:           'Prakash Natarajan'
  url:            https://twitter.com/iamprakashn

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

